apiVersion: v2
appVersion: "0.2.0.38"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
deprecated: false
description: An adult media thingy.
home: https://truecharts.org/charts/stable/whisparr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/whisparr.png
keywords:
  - whisparr
  - Downloaders
  - MediaApp-Other
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: whisparr
sources:
  - https://github.com/KE0QHN/catalog/tree/main/charts/whisparr
  - https://ghcr.io/hotio/whisparr:v2
type: application
version: 3.0.11
annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/catagories: |
    - Downloaders
    - MediaApp-Other
